#!/bin/bash

# This test file is executed against the 'latest' scenario in scenarios.json,
# which pairs 'fireconnect' with the 'node' feature it requires (FireConnect
# needs Node.js 18+). It is NOT run against the bare auto-generated devcontainer,
# because that would omit the 'node' dependency and the install would fail; the
# CI workflow therefore runs fireconnect via scenarios only
# (--skip-autogenerated).
#
# fireconnect installs the launcher at ~/.local/bin and appends that to the
# user's .bashrc. Non-interactive shells do not source .bashrc, so ~/.local/bin
# is prepended to PATH explicitly below. 'fireconnect help' exits 0 and requires
# no sign-in, so it is a safe assertion that the CLI is installed and runnable.
#
# Run locally (from the repo root):
#    devcontainer features test --features fireconnect --skip-autogenerated .
#
# See https://github.com/devcontainers/cli/blob/main/docs/features/test.md

set -e

# Optional: Import test library bundled with the devcontainer CLI.
# Provides the 'check' and 'reportResults' commands.
source dev-container-features-test-lib

export PATH="$HOME/.local/bin:$PATH"

check "fireconnect on PATH" command -v fireconnect
check "fireconnect help" fireconnect help

# Report results
# If any of the checks above exited with a non-zero exit code, the test will fail.
reportResults
